### ISSUE TITLE
希望增加Haskell高亮

### ISSUE THREAD

**Issue by ZQBCWG** [guobao2333/MT-syntax-highlight#5]
Thanks

**Comment by guobao2333** [comment]
你好，你需要提供一些有关于这个语言的资料，我才能尝试支持它，因为我不确定会不会存在歧义，而且最近我有点忙。

在我得到回复之后会尽快支持这个语言。

**Comment by ZQBCWG** [comment]
> 你好，你需要提供一些有关于这个语言的资料，我才能尝试支持它，因为我不确定会不会存在歧义，而且最近我有点忙。
> 
> 在我得到回复之后会尽快支持这个语言。

https://github.com/zenzike/src-highlite-haskell
这个应该有用

**Comment by guobao2333** [comment]
@ZQBCWG 根据官方网站的描述与教程，这个语言似乎只适用于控制台的I/O输入输出，我并不清楚为什么要在Android设备上的mt管理器中编写，甚至我都不知道这个语言有没有专用的文件后缀。
它好像是一个专注于数学运算的函数范式语言，而且我找到的资料几乎都是控制台使用，我不明白这语言你为什么想用mt管理器去编写……

**Comment by ZQBCWG** [comment]
> @ZQBCWG 根据官方网站的描述与教程，这个语言似乎只适用于控制台的I/O输入输出，我并不清楚为什么要在Android设备上的mt管理器中编写，甚至我都不知道这个语言有没有专用的文件后缀。 它好像是一个专注于数学运算的函数范式语言，而且我找到的资料几乎都是控制台使用，我不明白这语言你为什么想用mt管理器去编写……

本着增加更多的用途才有的想法和自己有在mt的终端用所以才提出的

**Comment by guobao2333** [comment]
> 本着增加更多的用途才有的想法和自己有在mt的终端用所以才提出的

但终端的语法高亮与普通的文件编辑器中的高亮并非同一实现

**Comment by ZQBCWG** [comment]
> > 本着增加更多的用途才有的想法和自己有在mt的终端用所以才提出的
> 
> 但终端的语法高亮与普通的文件编辑器中的高亮并非同一实现

haskell是有可执行代码的，可以使用::load等方式加载
剩下的在改了
